/**
 * The daily reading plan.
 *
 * Each entry is a single Bible chapter (so the API's verse numbers are
 * unambiguous) plus the verse to feature as the "verse of the day". The reading
 * for a given calendar day is chosen deterministically from the date — see
 * `getDailyReading` in services/bible.service — so every user sees the same
 * passage on the same day, and it rotates day to day.
 *
 * The list can grow toward 365 entries with no code change; selection wraps with
 * a modulo, so with N entries the cycle simply repeats every N days.
 */
export interface ReadingPlanEntry {
  /** A single chapter reference accepted by bible-api.com, e.g. "Psalm 23". */
  passage: string;
  /** The verse number within `passage` to feature as the verse of the day. */
  votdVerse: number;
}

export const READING_PLAN: ReadingPlanEntry[] = [
  { passage: "Psalm 23", votdVerse: 1 },
  { passage: "John 3", votdVerse: 16 },
  { passage: "Romans 8", votdVerse: 28 },
  { passage: "Philippians 4", votdVerse: 13 },
  { passage: "Jeremiah 29", votdVerse: 11 },
  { passage: "Proverbs 3", votdVerse: 5 },
  { passage: "Isaiah 40", votdVerse: 31 },
  { passage: "Psalm 46", votdVerse: 10 },
  { passage: "Joshua 1", votdVerse: 9 },
  { passage: "Matthew 6", votdVerse: 33 },
  { passage: "Psalm 91", votdVerse: 1 },
  { passage: "1 Corinthians 13", votdVerse: 4 },
  { passage: "Galatians 5", votdVerse: 22 },
  { passage: "Ephesians 2", votdVerse: 8 },
  { passage: "Psalm 1", votdVerse: 1 },
  { passage: "Psalm 27", votdVerse: 1 },
  { passage: "Psalm 121", votdVerse: 1 },
  { passage: "Psalm 139", votdVerse: 14 },
  { passage: "Isaiah 41", votdVerse: 10 },
  { passage: "Matthew 11", votdVerse: 28 },
  { passage: "John 14", votdVerse: 6 },
  { passage: "John 1", votdVerse: 1 },
  { passage: "Romans 12", votdVerse: 2 },
  { passage: "Hebrews 11", votdVerse: 1 },
  { passage: "James 1", votdVerse: 2 },
  { passage: "1 Peter 5", votdVerse: 7 },
  { passage: "2 Timothy 1", votdVerse: 7 },
  { passage: "Psalm 19", votdVerse: 1 },
  { passage: "Psalm 51", votdVerse: 10 },
  { passage: "Psalm 103", votdVerse: 1 },
  { passage: "Psalm 145", votdVerse: 8 },
  { passage: "Matthew 5", votdVerse: 3 },
  { passage: "Luke 6", votdVerse: 31 },
  { passage: "Romans 5", votdVerse: 8 },
  { passage: "Romans 10", votdVerse: 9 },
  { passage: "2 Corinthians 5", votdVerse: 17 },
  { passage: "Colossians 3", votdVerse: 23 },
  { passage: "1 Thessalonians 5", votdVerse: 16 },
  { passage: "Hebrews 12", votdVerse: 1 },
  { passage: "Hebrews 13", votdVerse: 8 },
  { passage: "James 4", votdVerse: 7 },
  { passage: "1 John 1", votdVerse: 9 },
  { passage: "1 John 4", votdVerse: 7 },
  { passage: "Revelation 21", votdVerse: 4 },
  { passage: "Genesis 1", votdVerse: 1 },
  { passage: "Exodus 14", votdVerse: 14 },
  { passage: "Deuteronomy 31", votdVerse: 6 },
  { passage: "Psalm 16", votdVerse: 8 },
  { passage: "Psalm 18", votdVerse: 2 },
  { passage: "Psalm 30", votdVerse: 5 },
  { passage: "Psalm 34", votdVerse: 8 },
  { passage: "Psalm 37", votdVerse: 4 },
  { passage: "Psalm 42", votdVerse: 1 },
  { passage: "Psalm 56", votdVerse: 3 },
  { passage: "Psalm 62", votdVerse: 1 },
  { passage: "Psalm 84", votdVerse: 10 },
  { passage: "Psalm 90", votdVerse: 12 },
  { passage: "Psalm 100", votdVerse: 1 },
  { passage: "Psalm 118", votdVerse: 24 },
  { passage: "Psalm 119", votdVerse: 105 },
  { passage: "Psalm 127", votdVerse: 1 },
  { passage: "Psalm 133", votdVerse: 1 },
  { passage: "Psalm 143", votdVerse: 8 },
  { passage: "Proverbs 16", votdVerse: 3 },
  { passage: "Proverbs 18", votdVerse: 10 },
  { passage: "Proverbs 31", votdVerse: 25 },
  { passage: "Ecclesiastes 3", votdVerse: 1 },
  { passage: "Isaiah 26", votdVerse: 3 },
  { passage: "Isaiah 53", votdVerse: 5 },
  { passage: "Isaiah 55", votdVerse: 8 },
  { passage: "Jeremiah 17", votdVerse: 7 },
  { passage: "Lamentations 3", votdVerse: 22 },
  { passage: "Micah 6", votdVerse: 8 },
  { passage: "Habakkuk 3", votdVerse: 17 },
  { passage: "Zephaniah 3", votdVerse: 17 },
  { passage: "Matthew 7", votdVerse: 7 },
  { passage: "Matthew 22", votdVerse: 37 },
  { passage: "Matthew 28", votdVerse: 19 },
  { passage: "Mark 12", votdVerse: 30 },
  { passage: "Luke 1", votdVerse: 37 },
  { passage: "John 8", votdVerse: 12 },
  { passage: "John 10", votdVerse: 10 },
  { passage: "John 11", votdVerse: 25 },
  { passage: "John 13", votdVerse: 34 },
  { passage: "John 15", votdVerse: 5 },
  { passage: "John 16", votdVerse: 33 },
  { passage: "Acts 1", votdVerse: 8 },
  { passage: "Acts 2", votdVerse: 38 },
  { passage: "Romans 1", votdVerse: 16 },
  { passage: "Romans 6", votdVerse: 23 },
  { passage: "Romans 15", votdVerse: 13 },
  { passage: "1 Corinthians 10", votdVerse: 13 },
  { passage: "1 Corinthians 15", votdVerse: 58 },
  { passage: "2 Corinthians 4", votdVerse: 16 },
  { passage: "2 Corinthians 12", votdVerse: 9 },
  { passage: "Galatians 2", votdVerse: 20 },
  { passage: "Galatians 6", votdVerse: 9 },
  { passage: "Ephesians 3", votdVerse: 20 },
  { passage: "Ephesians 4", votdVerse: 32 },
  { passage: "Ephesians 6", votdVerse: 10 },
  { passage: "Philippians 1", votdVerse: 6 },
  { passage: "Philippians 2", votdVerse: 3 },
  { passage: "Colossians 1", votdVerse: 15 },
  { passage: "1 Thessalonians 4", votdVerse: 16 },
  { passage: "2 Thessalonians 3", votdVerse: 3 },
  { passage: "1 Timothy 6", votdVerse: 6 },
  { passage: "2 Timothy 3", votdVerse: 16 },
  { passage: "Titus 3", votdVerse: 5 },
  { passage: "Hebrews 4", votdVerse: 12 },
  { passage: "Hebrews 10", votdVerse: 23 },
  { passage: "James 2", votdVerse: 17 },
  { passage: "James 3", votdVerse: 17 },
  { passage: "1 Peter 1", votdVerse: 3 },
  { passage: "1 Peter 2", votdVerse: 9 },
  { passage: "2 Peter 1", votdVerse: 3 },
  { passage: "1 John 3", votdVerse: 1 },
  { passage: "1 John 5", votdVerse: 4 },
  { passage: "Revelation 3", votdVerse: 20 },
  { passage: "Revelation 22", votdVerse: 13 },
];
